### PR TITLE
Unused variables

### PR DESCRIPTION
**Pull request by xp-1000**
crappy script to track any unused variable and fail the CI when meet

### CODE REVIEW

**Comment by xp-1000** [comment]
see https://github.com/claranet/terraform-signalfx-detectors/runs/919618253?check_suite_focus=true for example

**Comment by pdecat** [comment]
What about tflint? https://github.com/terraform-linters/tflint/pull/739

**Comment by pdecat** [comment]
Or a python implementation https://alexwlchan.net/2019/05/finding-unused-variables-in-a-terraform-module/

**Comment by xp-1000** [comment]
> Or a python implementation https://alexwlchan.net/2019/05/finding-unused-variables-in-a-terraform-module/

the pyhcl lib is not aims to fully support hcl, it fails on some of our modules (especially on locals and outputs) and implementation is long and do not allow exclusions.

> What about tflint? terraform-linters/tflint#739

better idea, I can test.

**Pull request merged**
