### PR TITLE
Detectors md

### PR DESCRIPTION
**Pull request by hlepesant**
When you have Raid Software disks managed by MD

### CODE REVIEW

**Comment by xp-1000** [comment]
hello @hlepesant, thanks for the contribution, I updated your fork:

- fetch upstream and rebase your branch which was outdated
- rename the module mdadm which seems more understandable
- import some info from README.md file missing from the conf/readme.yaml
- update the readme config to be clearer and more homogenous with others monitors
- use the jinja generator instead of writing the terraform files manually (this also fix lot of not compliant code like the missing transformation functio which is crucial)

As you can see, the detectors yaml files are pretty easy to create with very few lines.
I think you would avoid wasting lot of time if you use the dev environment and automation tools instead of trying to reproduce everything manually (which bring lot of errors and best practices not followed).

Please consider the pushed changes as hints for your future contribution.

Also don't forget you have permission to create branch, it is easier for me to help you when using it instead of fork. (also I don't know why but it seems the CI is not triggered from fork based PR :thinking: else it would have lot of "red" here :) )

**Review by hlepesant — COMMENTED** [review]
👍

**Comment by xp-1000** [comment]
PR rebased on : https://github.com/claranet/terraform-signalfx-detectors/tree/ci_from_fork

as we can see, all tests are triggered and OK now even if it is not perfect, see: https://github.com/claranet/terraform-signalfx-detectors/pull/269#issuecomment-812872101

we need to wait this PR to be merged before to merge the current.

**Review by xp-1000 — APPROVED** [review]

**Comment by hlepesant** [comment]
Tested on a customer. OK
All its detectors have switched to v1.4.0 successfully.
Good job

**Pull request merged**
