### PR TITLE
Fix integration_azure-mariadb

### PR DESCRIPTION
**Pull request by zfiel**

### CODE REVIEW

**Comment by xp-1000** [comment]
Hello,

it is not the first time, we noticed the same for postgresql: https://github.com/claranet/terraform-signalfx-detectors/pull/299

Microsoft still does not manage sensitive in 2022..

As for the previous PR I recommend to use `*` wildcard for any char because I am pretty sure that the 2 patterns exist on different orgs.

**Comment by Shr3ps** [comment]
> Hello,
> 
> it is not the first time, we noticed the same for postgresql: #299
> 
> Microsoft still does not manage sensitive in 2022..
> 
> As for the previous PR I recommend to use `*` wildcard for any char because I am pretty sure that the 2 patterns exist on different orgs.

👍 
Let's use again '*'

**Comment by zfiel** [comment]
> Hello,
> 
> it is not the first time, we noticed the same for postgresql: #299
> 
> Microsoft still does not manage sensitive in 2022..
> 
> As for the previous PR I recommend to use `*` wildcard for any char because I am pretty sure that the 2 patterns exist on different orgs.

Done.

**Review by Shr3ps — APPROVED** [review]

**Review by xp-1000 — APPROVED** [review]

**Comment by xp-1000** [comment]
@BzSpi @Shr3ps should you no do the same for azure-mysql?

**Pull request merged**
