### PR TITLE
Allow overriding `filter_defaults` field

### PR DESCRIPTION
**Pull request by chungktran**

### CODE REVIEW

**Review by xp-1000 — APPROVED** [review]
Thanks for your contribution.

I just renamed the local to avoid duplication for the compliant ci check.

I also added the variable to the wiki https://github.com/claranet/terraform-signalfx-detectors/wiki/Variables#filter_defaults

Before to release, I will update modules which do not use the common modules.tf file (basically everything not based on the agent) to make this new feature available for all.

**Comment by chungktran** [comment]
@xp-1000 Thanks for fixing and merging this.

**Comment by xp-1000** [comment]
@chungktran before to release the 1.6.0 I would like to extend this mechanism to all modules (not only the smart agent based).

I opened https://github.com/claranet/terraform-signalfx-detectors/pull/284 which should respect the goal of your PR.

may be can you give a try and let me know if it seems good for you?

thanks

**Comment by chungktran** [comment]
@xp-1000 I've tested the smart agent piece using the branch in PR 284 and it's working as expected. Thanks for making the change.

**Comment by xp-1000** [comment]
cool, thanks for the quick answer, I will wait for a review approval, merge it and release the v.1.6.0 ;)

**Comment by chungktran** [comment]
That's awesome!

**Comment by xp-1000** [comment]
Hello @chungktran the 1.6.0 is available: https://github.com/claranet/terraform-signalfx-detectors/releases/tag/v1.6.0 :rocket:

**Comment by chungktran** [comment]
@xp-1000 Nice! Thanks a bunch.

**Pull request merged**
